const queryKeys = {
  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_OPERATOR_TIMETABLE: "GET_OPERATOR_TIMETABLE",
  GET_USER_REFERRED: "GET_USER_REFERRED",
  GET_USER_ADVERT: "GET_USER_ADVERT",
  GET_DASHBOARD_INFO: "GET_DASHBOARD_INFO",
  GET_LOTTO_OPERATOR: "GET_LOTTO_OPERATOR",
  GET_LOTTO_GAMES: "GET_LOTTO_GAMES",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_TRANSACTION: "GET_ALL_TRANSACTION",
  GET_ALL_WITHDRAW: "GET_ALL_WITHDRAW",
};

export default queryKeys;
