const queryKeys = {
  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_OPERATOR_TIMETABLE: "GET_OPERATOR_TIMETABLE",
  GET_USER_REFERRED: "GET_USER_REFERRED",
  GET_USER_ADVERT: "GET_USER_ADVERT",
  GET_DASHBOARD_INFO: "GET_DASHBOARD_INFO",
  GET_LOTTO_OPERATOR: "GET_LOTTO_OPERATOR",
};

export default queryKeys;
